plugins {
    id 'java'
    id("com.gradleup.shadow") version "8.3.8"
    id 'org.graalvm.buildtools.native' version '0.11.0'
}

group = 'com.fullsteam'
version = '1.0.0-SNAPSHOT'

repositories {
    mavenCentral()
}

def nettyVersion = "4.2.3.Final"
def jacksonVersion = "2.19.2"
def logbackVersion = "1.5.13"

dependencies {
    implementation "io.netty:netty-transport:${nettyVersion}"
    implementation "io.netty:netty-codec-http:${nettyVersion}"
    implementation "io.netty:netty-handler:${nettyVersion}"
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
    implementation "com.fasterxml.jackson.module:jackson-module-afterburner:${jacksonVersion}"
    implementation "ch.qos.logback:logback-classic:${logbackVersion}"
    implementation "org.apache.commons:commons-lang3:3.18.0"

    testImplementation platform("org.junit:junit-bom:5.10.0")
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

shadowJar {
    mergeServiceFiles()
    manifest {
        attributes 'Main-Class': 'com.fullsteam.GameServer'
    }
    archiveBaseName.set('full-steam')
    archiveVersion.set(project.version)
    archiveClassifier.set('')
    zip64 = true
}

graalvmNative {
    binaries {
        main {
//             imageName = 'application'
            mainClass = 'com.fullsteam.GameServer'
//             debug = true
//             verbose = true
//             fallback = true
//             sharedLibrary = false
//             quickBuild = false
//             richOutput = false
//
//             systemProperties = [name1: 'value1', name2: 'value2']
//             configurationFileDirectories.from(file('src/my-config'))
//             excludeConfig.put("org.example.test:artifact:version", ["^/META-INF/native-image/.*", "^/config/.*"])
//             excludeConfig.put(file("path/to/artifact.jar"), listOf("^/META-INF/native-image/.*", "^/config/.*"))
//
//             // Advanced options
//             buildArgs.add('--link-at-build-time')
//             jvmArgs.add('flag')
//
//             // Runtime options
//             runtimeArgs.add('--help')

            useFatJar = true
//             buildArgs.add('--verbose')
            buildArgs.add('--add-opens=java.base/java.nio=ALL-UNNAMED')
            buildArgs.add('--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED')
            buildArgs.add('--add-opens=java.base/jdk.internal.ref=ALL-UNNAMED')
            buildArgs.add('--trace-class-initialization=ch.qos.logback.classic.Logger')
            buildArgs.add('--trace-object-instantiation=ch.qos.logback.core.AsyncAppenderBase$Worker')
            buildArgs.add('--initialize-at-build-time=org.slf4j.LoggerFactory,ch.qos.logback')
            buildArgs.add('--initialize-at-run-time=io.netty')
        }

        all {
            resources.autodetect()
        }
    }
}
